spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/campus_club?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:2636888165}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  flyway:
    enabled: false

logging:
  level:
    com.erokin.campusclubmanagement: INFO

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-this-secret-in-production-please-change}
      expiration-ms: 86400000
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

server:
  port: ${SERVER_PORT:8123}
