spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/campus_club?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:2636888165}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  flyway:
    enabled: false

logging:
  level:
    com.erokin.campusclubmanagement: INFO

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-this-secret-in-production-please-change}
      expiration-ms: 86400000
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

server:
  port: ${SERVER_PORT:8123}

aliyun:
  oss:
    enabled: ${ALIYUN_OSS_ENABLED:false}
    endpoint: ${ALIYUN_OSS_ENDPOINT:https://oss-cn-hangzhou.aliyuncs.com}
    region: ${ALIYUN_OSS_REGION:cn-hangzhou}
    bucket: ${ALIYUN_OSS_BUCKET:campus-club-sample}
    base-path: ${ALIYUN_OSS_BASE_PATH:}
    public-domain: ${ALIYUN_OSS_PUBLIC_DOMAIN:}
    default-url-expiry: ${ALIYUN_OSS_URL_EXPIRY:PT1H}
  speech:
    enabled: ${ALIYUN_SPEECH_ENABLED:false}
    region-id: ${ALIYUN_SPEECH_REGION:cn-shanghai}
    endpoint-name: ${ALIYUN_SPEECH_ENDPOINT_NAME:cn-shanghai}
    product: ${ALIYUN_SPEECH_PRODUCT:nls-filetrans}
    domain: ${ALIYUN_SPEECH_DOMAIN:filetrans.cn-shanghai.aliyuncs.com}
    api-version: ${ALIYUN_SPEECH_API_VERSION:2018-08-17}
    version: ${ALIYUN_SPEECH_VERSION:4.0}
    app-key: ${NLS_APP_KEY:}
    access-key-id: ${ALIYUN_AK_ID:}
    access-key-secret: ${ALIYUN_AK_SECRET:}
    enable-words: true
    poll-interval: ${ALIYUN_SPEECH_POLL:PT3S}
    max-poll-attempts: ${ALIYUN_SPEECH_ATTEMPTS:40}
