spring:
  application:
    name: campus-club-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_club_management?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 2636888165
server:
  port: 8123
  servlet:
    context-path: /api


