package com.erokin.campusclubmanagement.dto.video;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class SubtitleEditRequest {

    private Long id;

    @NotNull
    @Min(1)
    private Integer sequence;

    @NotNull
    @Min(0)
    private Integer startMs;

    @NotNull
    @Min(1)
    private Integer endMs;

    @NotBlank
    @Size(max = 500)
    private String text;

    private boolean autoGenerated;
}
