package com.erokin.campusclubmanagement.dto.video;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class SubtitleSegmentResponse {
    private Long id;
    private Integer sequence;
    private Integer startMs;
    private Integer endMs;
    private String text;
    private boolean autoGenerated;
}
