import api from './http';
import type { PromoVideo, SubtitleSegment } from '../types/models';

export const fetchClubPromoVideo = async (clubId: number) => {
  const { data } = await api.get<PromoVideo>(`/api/clubs/${clubId}/promo-video`);
  return data;
};

export const uploadClubPromoVideo = async (clubId: number, file: File, durationSeconds: number) => {
  const formData = new FormData();
  formData.append('file', file);
  formData.append('durationSeconds', String(durationSeconds));
  const { data } = await api.post<PromoVideo>(`/api/clubs/${clubId}/promo-video`, formData, {
    headers: { 'Content-Type': 'multipart/form-data' },
  });
  return data;
};

export const generateClubPromoVideoSubtitles = async (clubId: number) => {
  const { data } = await api.post<PromoVideo>(`/api/clubs/${clubId}/promo-video/subtitles/ai`);
  return data;
};

export const saveClubPromoVideoSubtitles = async (clubId: number, subtitles: SubtitleSegment[]) => {
  const payload = {
    subtitles: subtitles.map((item) => ({
      sequence: item.sequence,
      startMs: item.startMs,
      endMs: item.endMs,
      text: item.text,
      autoGenerated: item.autoGenerated,
    })),
  };
  const { data } = await api.put<PromoVideo>(`/api/clubs/${clubId}/promo-video/subtitles`, payload);
  return data;
};
